# delimit ;
noisily {;

*use "Users/RayDuch/Dropbox/Projects/Book00/Stata do files/Utility and Label Files/Data/DV_8_IV_8_1.dta", clear;
*use "/Users/RayDuch/Dropbox/Projects/Book00/Stata do files/Utility and Label Files/data/DV_8_IV_8_1.dta";
use "~/Dropbox/Duch Stevenson Replication/DV_8_IV_8_1.dta";
*use "E:\Projects\Book00\Stata do files\Utility and Label Files\Data\DV_8_IV_8_1.dta", clear;

*drop studygroup;

label variable studytyp "NES or EB";
	label define studytyp 1 "nes" 2 "eb", modify;
	label values studytyp studytyp;
label variable studysyr "year survey started";
label variable studysmo "month survey started"; 
label variable studyeyr "year survey ended";
label variable studyemo "month survey ended"; 
label variable cnumb "country number";
label variable studynum "study id number";
label variable gnumb "party-group number";
label variable relelyr "year of most proximate election";
label variable relelmo "month of most proximate election";
label variable lastelyr "year of last election";
label variable lastelmo "month of last election";
label variable coalmin "coalition and minority status of incumbent government";
	label define coalmin 1 "SP Min" 2 "Coal Min" 3 "Coal Maj" 4 "SP Maj", modify;
	label values coalmin coalmin;
label variable incumb "1 = party-group contains incumbent pm or partner(s)";
label variable pm "1 = party-group contains the incumbent pm";
*rename wright_left wleft_right;
label variable wleft_right "party-group Left-Right position from manifestos, where large #s are rightist" ;
label variable wplaneco "party-group manifesto emphasis on planning, where large #s are more planning"; 
label variable wmarkeco "party-group manifesto emphasis on free market, where large #'s are more market"; 
label variable wwelfare "party-group manifesto emphasis on welfare,where larger #s are more welfare"; 
label variable year "same as studysyr";
label variable month "same as studysmo";
label variable mergeyr "equals studysyr if studysmo <= 6, else equals studysyr";
label variable wma11LR "11 year Moving Avg of left_right pos";
label variable wma11MP "11 year Moving Avg of protection emph";
label variable wma11EE "11 year Moving Avg of econ emphasis";
label variable sumpmper60 "sum over group: % years since 1960 pty was pm";
label variable sumincper60 "sum over group: % years since 1960 pty was inc";
label variable sumfinper60 "sum over group: % years since 1960 pty was finance minister";
label variable sumdepper60 "sum over group: % years since 1960 pty was deputy pm";
label variable sumecoper60 "sum over group: % years since 1960 pty was econ aff minister";
label variable sumptper60 "sum over group: % years since 1960 pty was partner";
label variable summinper60 "sum over group: average percent ministries held since 1960 ";


*label variable sumlabper60 "sum over group: % years since 1960 pty was labor minister";
*label variable sumeduper60 "sum over group: % years since 1960 pty was education minister";
*label variable sumheaper60 "sum over group: % years since 1960 pty was health minister";
*label variable sumhouper60 "sum over group: % years since 1960 pty was housing minister";
*label variable sumagrper60 "sum over group: % years since 1960 pty was agriculture minister";
*label variable sumindper60 "sum over group: % years since 1960 pty was trade & industry minister";
*label variable sumpubper60 "sum over group: % years since 1960 pty was public works minister";

label variable pmper60 "mean over group: % years since 1960 pty was pm";
label variable incper60 "mean over group: % years since 1960 pty was inc";
label variable finper60 "mean over group: % years since 1960 pty was finance minister";
label variable depper60 "mean over group: % years since 1960 pty was deputy pm";
label variable ecoper60 "mean over group: % years since 1960 pty was econ aff minister";

label variable ptper60 "mean over group: % years since 1960 pty was partner";
label variable minper60 "mean over group: average percent ministries held since 1960 ";
label variable minper60 "mean over group: average percent ministries held since 1960 ";
label variable tecper60 "mean over group: average percent ministries held by tecs since 1960 ";
label variable jrtecper60 "mean over group: average percent jr ministries held by tecs since 1960 ";
label variable alltecper60 "mean over group: average percent ministries and jr held by techs since 1960 ";

*label variable labper60 "mean over group: % years since 1960 pty was labor minister";
*label variable eduper60 "mean over group: % years since 1960 pty was education minister";
*label variable heaper60 "mean over group: % years since 1960 pty was health minister";
*label variable houper60 "mean over group: % years since 1960 pty was housing minister";
*label variable agrper60 "mean over group: % years since 1960 pty was agriculture minister";
*label variable indper60 "mean over group: % years since 1960 pty was trade & industry minister";
*label variable pubper60 "mean over group: % years since 1960 pty was public works minister";

label variable votemackie "party-group vote share from mackie and rose";
label variable votemani "party-group vote share from manifestos";
label variable partyprop "(seat-vote)/(vote) - (non-weighted mean of groups)";
label variable hsysvol "20 year MA of system electoral volatility";
label variable hsysprop "20 year MA of system proportionality - gallagher";
label variable hptyvote "10 year MA of party vote - (non-weighted mean of groups)";
label variable whptyvote "10 year MA of party vote - (weighted mean of groups)";
label variable whptyprop "10 year MA of party proportionality - (weighted mean of groups)";
label variable mjcper60 "% years since 1960 system had majority coalitions";
label variable mncper60 "% years since 1960 system had minority coalitions";
label variable mjsper60 "% years since 1960 system had majority SP govs";
label variable mnsper60 "% years since 1960 system had minority SP govs";
label variable votetype "is dependent variable in mlogit reported vote or voteintention?";
	label define vttype 1 "vote intention" 2 "post vote", modify;
	label values votetype vttype ;
label variable ptname "string party name";
label variable rnnobs "number of obs in the mlogit";
label variable rnaltest "overall test of sig of econ coeffcients";
label variable rneqtest "test of sig of econ coef. in each party-group equation";
label variable rnfreq "vote frequencies in raw data for party-group";
label variable rnnparam "number of parameters estimated in mlogit";
label variable rnptyobs "number of observations voting for party-group";
label variable rnpvSPmn "predicted value of vote probabilities";
label variable rndwSPmn "predicted value of vote probs, retnat real value to 1 worse";
label variable rndbSPmn "predicted value of vote probs, retnat real value to1 better";
label variable rndwSPsm "simulated change in vote prob, retnat real value to 1 worse";
label variable rndwSPss "standard deviation of rndwSPsm";
label variable rndwSPsu "95% upper bound of rndwSPsm";
label variable rndwSPsl "95% lower bound of rndwSPsm";
label variable rnjwSPsm "simulated change in vote prob, retnat 2 to 3 for all";
label variable rnlpvSPsm "logits - predicted value of vote probabilities";
label variable rnldwSPsm "logits - predicted value of vote probs, retnat real value to 1 worse";
label variable rnldbSPsm "logits - predicted value of vote probs, retnat real value to 1 better";
label variable rnljwSPsm "logits - simulated change in vote prob, retnat 2 to 3 for all";
label variable cname "string country full name";
label variable rndwvol "system level volatility calcualted from rndwSPsm";
label variable rnjwvol "system level volatility calculated from rnjwSPsm";
label variable protectsd "st. dev. of dist of pty positions on protectionism - all ptys in mani data";
label variable marplansd "st. dev. of dist of pty positions on market vs. planning - all ptys in mani data";
};
